### ISSUE TITLE
VE Restriction Enzyme Manager - several problems

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/Peony-Issue-Tracking#103]
_From @njhillson on October 18, 2015 18:11_

In VE, in Tools -> Restriction Enzymes Manager, there are several problems:

1) Built-in groups e.g. "Common Enzymes" are duplicated several times in Enzyme Groups list.

2) User-defined group saving is not working.

3) Rendered view of active enzymes is not sync'd with actual active enzymes list. For example, if I start with common enzymes active and turn on view cut sites, everything looks good. Then I go into the manager and remove all enzymes from the active group list and save. Still looks good. But, when go back to the manager, the manager suggests that the full common enzyme group is active, when nothing is active.

_Copied from original issue: TeselaGen/ve#1456_

**Comment by craftjk** [comment]
_From @mfero on October 31, 2015 1:47_

1) Built-in groups does not seem to be duplicated anymore.
**2) User defined group saving is not working... when I create a new group, then hit OK, the list disappears from the interface.  It does become active... but the list does not appear in the right hand panel of the restriction enzyme manager when selected in the right hand dropdown.**
3) rendered views seems to be sync'd now.

**Comment by tnrich** [comment]
@mfero, I'm having trouble replicating this issue. Can someone else try this and see if it works for them?

**Comment by mfero** [comment]
We do have intermittent issues it is true. Let me see if I can replicate...

**Comment by mfero** [comment]
this is still happening... I'll call you and walk you through the sequence...

**Comment by tnrich** [comment]
sounds good

**Comment by mfero** [comment]
ok,  we understand the issues... will close this in favor of enhancement.

**Comment by tnrich** [comment]
closing this. Mike will make an enhancement ticket that aims to solve the odd UX experience.
