### ISSUE TITLE
Data should be encrypted at rest and in transit

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/Peony-Issue-Tracking#43]
_From @sampearl on August 19, 2015 21:42_

Time to dive into the bcrypt library. I will get clarity on what data needs to be encrypted.

_Copied from original issue: TeselaGen/ve#1248_

**Comment by craftjk** [comment]
_From @sampearl on August 19, 2015 21:57_

List of data required to be encrypted at rest:
* All Passwords
* &lt;insert more here>

**Comment by rpavez** [comment]
Password are currently encrypted, also optionally appconfig.json can be be encrypted and loaded using a password when starting the app. What other fields should be encrypted?

Currently in-transit encryptation is working when using https, also password are encrypted by using a crypto hash representation.

**Comment by craftjk** [comment]
This has been fixed but is not testable
